### ISSUE TITLE
why add “added_values”

### ISSUE THREAD

**Issue by Young1993** [OhadRubin/SmBop#11]
Hi, I see in the spider.py
added_values = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "yes",
    "no",
    "y",
    "t",
    "f",
    "m",
    "n",
    "null",
]

I've not just figured out why do we need to add these values in entities?

**Comment by Young1993** [comment]
@OhadRubin  Hi  
In my understanding, you choose a similar model from "extractive question answering (Rajpurkar et al., 2016)", that could select words that may be DB values and added_values just as the default values. 
you mean in BRIDGE, they use the "copy mechanism " which is better than yours,

Is my understanding correct?

**Comment by OhadRubin** [comment]
No, we are able to copy from the question as well.
Cases we cannot handle for example are the following:
```
Question: "What are the names of all the french actors?"
Query: SELECT actor.name WHERE actor.country="France"
```
Our model will be able to answer:
```
SELECT actor.name WHERE actor.country="french"
```

But BRIDGE does IR on the schema on the actor.country column so the input to the model includes the tokens for "France". Because the distance from "french" and "France" it will be included there as well.
This method is very nice and could be integrated to SmBop very nicely.

**Comment by Young1993** [comment]
Wow, Thanks a lot for your interpretation, let's try it!

**Comment by alan-ai-learner** [comment]
@yonatansito  have you try to integrate it with SmBop?

> Yes, we are able to copy from the question as well.
> Cases we cannot handle for example are the following:
> 
> ```
> Question: "What are the names of all the french actors?"
> Gold Query: SELECT actor.name WHERE actor.country="France"
> ```
> 
> Our model will be able to answer:
> 
> ```
> SELECT actor.name WHERE actor.country="french"
> ```
> 
> But BRIDGE does IR on the schema on the actor.country column so the input to the model includes the tokens for "France" (because the edit distance from "french" and "France" is small) .
> This method is very nice and could be integrated to SmBop very nicely.
