### ISSUE TITLE
About multi GPUs for training

### ISSUE THREAD

**Issue by Young1993** [OhadRubin/SmBop#14]
Hi, again

I wanna use multi GPUs, whether just add 
`"distributed": {
    "cuda_devices": [0, 1, 2],
  }`

in defaults.jsonnet is enough?

**Comment by OhadRubin** [comment]
I suggest you look up this guide:
https://medium.com/ai2-blog/tutorial-how-to-train-with-multiple-gpus-in-allennlp-c4d7c17eb6d6
If you need more help, let me kno2.

**Comment by OhadRubin** [comment]
I wanted to mention that I found no no need for the multi-gpu setup. , since I found that training with smaller a batch size of around 20 is also pretty good.

**Comment by OhadRubin** [comment]
Hey, so I tried it myself, and adding ` "distributed": {"cuda_devices": [0,1]  },` gives the following error:
```
RuntimeError: Expected to mark a variable ready only once. This error is caused
by one of the following reasons:

1) Use of a module parameter outside the `forward` function. Please make sure
model parameters are not shared across multiple concurrent forward-backward
passes

2) Reused parameters in multiple reentrant backward passes. For example, if you
use multiple `checkpoint` functions to wrap the same part of your model, it
would result in the same set of parameters been used by different reentrant
backward passes multiple times, and hence marking a variable ready multiple
times. DDP does not support such use cases yet.

3) Incorrect unused parameter detection. The return value of the `forward`
function is inspected by the distributed data parallel wrapper to figure out if
any of the module's parameters went unused. For unused parameters, DDP would
not expect gradients from then. However, if an unused parameter becomes part of
the autograd graph at a later point in time (e.g., in a reentrant backward when
using `checkpoint`), the gradient will show up unexpectedly. If all parameters
in the model participate in the backward pass, you can disable unused parameter
detection by passing the keyword argument `find_unused_parameters=False` to
`torch.nn.parallel.DistributedDataParallel`.
```
@epwalsh can you chime in?

**Comment by epwalsh** [comment]
I haven't seen this before. If (3) is the reason, then we could add an option to set `find_unused_parameters` to `False` instead of `True` here:

https://github.com/allenai/allennlp/blob/fd5c9e4ce521dbb3a73d5bedd8d5666cfcf0e58d/allennlp/training/trainer.py#L380

**Comment by OhadRubin** [comment]
I got it working with `find_unused_parameters=False` ,  `"gradient_checkpointing":false` and by lowering the batch size to 5, but this causes the model to be incredibly slow.

**Comment by epwalsh** [comment]
That's not ideal 😏

Well FWIW I'm working on integrating FairScale into AllenNLP right now. That should allow you to use a much larger batch size even without gradient checkpointing.

**Comment by Young1993** [comment]
Hi @epwalsh I have tried but get the similar errors:

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 

1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes

2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.
```

Do you know the reason?

**Comment by epwalsh** [comment]
@Young1993, can you provide some more context? What model are you training? What does your config look like?
