### ISSUE TITLE
 ValueError: TextField's token_indexers have not been set.

### ISSUE THREAD

**Issue by varunpandya2004** [OhadRubin/SmBop#18]
I get the following error on running the demo notebook on colab. I have not made any changes to your code

ValueError: TextField's token_indexers have not been set.
Did you forget to call DatasetReader.apply_token_indexers(instance) on your instance?
If apply_token_indexers() is being called but you're still seeing this error, it may not be implemented correctly..

**Comment by OhadRubin** [comment]
Yeah, I forgot to update the demo.
It should be good now.

**Comment by varunpandya2004** [comment]
Yup works now! Thank you for this amazing model

**Comment by Muradean** [comment]
Hi, I also got the same error on eval.py cause this line was missing:

`predictor._dataset_reader.apply_token_indexers(instance)`

before the with torch.cuda.amp.autocast(enabled=True):

![A](https://user-images.githubusercontent.com/14300941/118433306-9985c400-b6d2-11eb-9e03-6e0725fd783c.png)

Here is a pull request with the needed line in case you wanna merge it:

https://github.com/OhadRubin/SmBop/pull/19
