### ISSUE TITLE
Question about the Representation of Query Trees

### ISSUE THREAD

**Issue by Young1993** [OhadRubin/SmBop#21]
Hi, 
I'd like to confirm 3  points of confusion:

1. The operation of **join** is absent in relational algebra grammar，is it possible that causes Search errors(52%) you mentioned in the paper?
2. And, what's the meaning of the unary ops' **literal**?
3. I have seen that you have decreased the `self._num_values = 15` to  10, whether the 10 is enough, due to the mention words in the question that related to schema normally less than 10

Looking forward to your reply

**Comment by OhadRubin** [comment]
1. The `join` operation is handled both in the pre-processing and post-processing. 
2. This is just part of the pre-processing to account for quotation marks.
3. Yeah, 10 is enough.

**Comment by Young1993** [comment]
Thanks
