### ISSUE TITLE
Resume training with the pretrained model

### ISSUE THREAD

**Issue by Muradean** [OhadRubin/SmBop#22]
Hi,

I've trained a SmBop model from scratch with the 8659 instances instead of the 7000 and got better results, however they were still worse than the pre-trained model. So currently I am trying to continue training the pre-trained model with the 8659 instances to see if I can get further improvements.

However, I am not being able to resume training on the pre-trained model provided on this page:

This is what I am currently doing: 

python resume.py --dir /app/SmBop/experiments/pretrained_model --gpu 0

However, it seems the training is starting from scratch instead of resuming (As it can be seen by the very low validation score):

![a](https://user-images.githubusercontent.com/14300941/119293919-47e9b600-bc4b-11eb-8498-d1343d729490.png)

Should I need to change the weights.th file ? What can I do to resume training with the best pretrained model available ?

**Comment by Muradean** [comment]
nevermind, I just changed the filename (weights.th) and managed to resume training

**Comment by alan-ai-learner** [comment]
> nevermind, I just changed the filename (weights.th) and managed to resume training

what and where you changes the file name? please help im facing the same issue? @OhadRubin @Muradean
