### ISSUE TITLE
Example of config.json for resume.py

### ISSUE THREAD

**Issue by Illumaria** [OhadRubin/SmBop#23]
Hello! According to the code of [resume.py](https://github.com/OhadRubin/SmBop/blob/main/resume.py), some configuration (namely `config.json`) has to be provided. What should be inside? Can you provide a link to an example config file, please?

**Comment by OhadRubin** [comment]
Hey, the --dir argument is the serialization directory, and the config.json is the output of the original run's  `defaults.jsonnet` file compiled into `.json`
This is a workaround to allow resuming on a GPU different from the original run.

**Comment by Illumaria** [comment]
I see, thank you!

**Comment by varunpandya2004** [comment]
How to fine-tune the model on our own dataset, without needing to retrain it again? Can the pretrained model you provided be used for this?
