### ISSUE TITLE
 CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.24 GiB already allocated; 4.50 MiB free; 1.24 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by anumi1999** [OhadRubin/SmBop#24]
Hi! I tried to train the model and encountered this problem.

I tried to decrease the batch size too but the problem persisted. 
![image](https://user-images.githubusercontent.com/52823306/120101890-0df64380-c166-11eb-85f6-193166271378.png)

Can someone please help me with this?

**Comment by OhadRubin** [comment]
What GPU are you using? (How much memory?)

**Comment by anumi1999** [comment]
> What GPU are you using? (How much memory?)

My GPU memory is 2 GB. But when I tried to train it on colab with 14 gb gpu then too the problem persists.

**Comment by OhadRubin** [comment]
Did you use --batch_size 1 on colab?

**Comment by anumi1999** [comment]
> Did you use --batch_size 1 on colab?

Yes but it stopped in between.

**Comment by OhadRubin** [comment]
You mean OOM?
Can you share the log?

**Comment by OhadRubin** [comment]
I guess this is stale?
Closed.
