### ISSUE TITLE
EM evaluation failed

### ISSUE THREAD

**Issue by realningzheng** [OhadRubin/SmBop#25]
Hi there,

Thanks for releasing the code. I ran the model with a filtered spider dataset excluding extra hard samples. However I encountered errors below, although the training process can still go on, the evaluation accuracy is 0. Any idea on this situation?
![image](https://user-images.githubusercontent.com/60973275/123267573-bf9f4f00-d52f-11eb-9f11-b0f9a6006473.png)

**Comment by OhadRubin** [comment]
Hey, 
In [this](https://github.com/OhadRubin/SmBop/blob/bb15fc28d68b3bf4cfb17fc7fc4a543897cc225c/smbop/models/smbop.py#L810) line, there is a try except block which is failing, can you removing and let me know what the actual exception is?
