### ISSUE TITLE
Hos is reranking applied in the code?

### ISSUE THREAD

**Issue by entslscheia** [OhadRubin/SmBop#27]
Hi,

It seems like I could not find the code related to the reranking part described in the paper. Several config options like "cntx_reranker" and "should_rerank" are not actually used. Could you please give me some hints on that? Many thanks!

**Comment by OhadRubin** [comment]
The final version of the paper does not using the reranker.
Implementing it is quite easy, just apply a linear layer, apply cross entropy and take the root gold hash as supervision.

**Comment by entslscheia** [comment]
Appreciate it!
