### ISSUE TITLE
How to get the confidence of a prediction?

### ISSUE THREAD

**Issue by entslscheia** [OhadRubin/SmBop#28]
I am trying to get the confidence of each prediction from SmBop. In your code, it seems like to make the final prediction, only the score for the last decoding step is needed, i.e., in [this line](https://github.com/OhadRubin/SmBop/blob/0c5dd39b870d8ecde5d40a846219ae03e7aa21f1/smbop/models/smbop.py#L779) all other scores are set as the minimum. So can I just use the max score in `beam_scores_el` there as the confidence of a prediction? Or is there any more reasonable way to do it? Any suggestions would be greatly appreciated!

**Comment by OhadRubin** [comment]
Yeah, using the score of `beam_scores_el` sounds reasonable.
I suggest you also tune it using the method described here: https://arxiv.org/abs/1706.04599

**Comment by entslscheia** [comment]
Thanks for your advice!

**Comment by ManasiPat** [comment]
What is beam_scores_el mathematically? Are these ( sum/ average/ product?) of log probabilities of each predicted token of each beam?  what do the dimension of this tensor indicate?  @entslscheia  @OhadRubin please answer at your earlies convenience. Thanks.
