### ISSUE TITLE
How do I make predictions on Custom Data

### ISSUE THREAD

**Issue by nikhilcss97** [OhadRubin/SmBop#29]
I made the `store_small.sqlite` and `schema.sql` files in a folder called `store_small` and placed this folder inside the spider `database` folder.
Now, when I try to select this database in the colab notebook, it gives out a `KeyError: 'store_small'` .

How should I make inferences and run custom queries on this database? Someone, please help me out here.

The traceback:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-9-714b9f458c15> in <module>()
     26       )
     27       return out[0]["sql_list"]
---> 28 inference("How many regions are there?","store_small")

<ipython-input-9-714b9f458c15> in inference(question, db_id)
     18 def inference(question,db_id):
     19   instance = predictor._dataset_reader.text_to_instance(
---> 20       utterance=question, db_id=db_id,
     21   )
     22   predictor._dataset_reader.apply_token_indexers(instance)

/content/SmBop/smbop/dataset_readers/spider.py in text_to_instance(self, utterance, db_id, sql, sql_with_values)
    316             )
    317 
--> 318         desc = self.enc_preproc.get_desc(tokenized_utterance, db_id)
    319         entities, added_values, relation = self.extract_relation(desc)
    320 

/content/SmBop/smbop/dataset_readers/enc_preproc.py in get_desc(self, tokenized_utterance, db_id)
    193             text=[x.text for x in tokenized_utterance[1:-1]],
    194             code=None,
--> 195             schema=self.schemas[db_id],
    196             orig=None,
    197             orig_schema=self.schemas[db_id].orig,

KeyError: 'store_small'
```

**Comment by hXtreme** [comment]
You need to provide the sql schema as a JSON as described [here](https://github.com/taoyds/spider#tables) and then append the json data to `dataset/tables.json`. I know its not fun.

FYI: I'm not part of the SmBop team, just a randomly walking stranger.

**Comment by alan-ai-learner** [comment]
> I made the `store_small.sqlite` and `schema.sql` files in a folder called `store_small` and placed this folder inside the spider `database` folder.
> Now, when I try to select this database in the colab notebook, it gives out a `KeyError: 'store_small'` .
> 
> How should I make inferences and run custom queries on this database? Someone, please help me out here.
> 
> The traceback:
> 
> ```
> KeyError                                  Traceback (most recent call last)
> <ipython-input-9-714b9f458c15> in <module>()
>      26       )
>      27       return out[0]["sql_list"]
> ---> 28 inference("How many regions are there?","store_small")
> 
> <ipython-input-9-714b9f458c15> in inference(question, db_id)
>      18 def inference(question,db_id):
>      19   instance = predictor._dataset_reader.text_to_instance(
> ---> 20       utterance=question, db_id=db_id,
>      21   )
>      22   predictor._dataset_reader.apply_token_indexers(instance)
> 
> /content/SmBop/smbop/dataset_readers/spider.py in text_to_instance(self, utterance, db_id, sql, sql_with_values)
>     316             )
>     317 
> --> 318         desc = self.enc_preproc.get_desc(tokenized_utterance, db_id)
>     319         entities, added_values, relation = self.extract_relation(desc)
>     320 
> 
> /content/SmBop/smbop/dataset_readers/enc_preproc.py in get_desc(self, tokenized_utterance, db_id)
>     193             text=[x.text for x in tokenized_utterance[1:-1]],
>     194             code=None,
> --> 195             schema=self.schemas[db_id],
>     196             orig=None,
>     197             orig_schema=self.schemas[db_id].orig,
> 
> KeyError: 'store_small'
> ```

Hey  @nikhilcss97  how did you made the schema, please let me know?
