### ISSUE TITLE
Is it possible to share the trained model?

### ISSUE THREAD

**Issue by shuqinlee** [OhadRubin/SmBop#3]
Thank you for sharing the code! It will be very kind of you guys to share the trained model. 
Looking forward to it!

**Comment by OhadRubin** [comment]
Yes, see the README for a link.

**Comment by shuqinlee** [comment]
Thank you for replying. I have tried the link, seems that it is canceled?
there is a 404 error.

OhadRubin ***@***.***> 于2021年4月25日周日 下午2:11写道：

**Comment by OhadRubin** [comment]
It is up for me (even on incognito mode).
The link is  https://drive.google.com/file/d/1pQvg2sT7h9t_srgmN1nGGMfIPa62U9ag/view?usp=sharing
