### ISSUE TITLE
Documentation of smbop module for better understanding

### ISSUE THREAD

**Issue by awasthiabhijeet** [OhadRubin/SmBop#30]
Hi @OhadRubin,

Congratulations on this great work and thank you for open-sourcing the code.

It would be very helpful if you could also provide some documentation for the code inside [smbop](https://github.com/OhadRubin/SmBop/tree/main/smbop) module. 
I'm finding it a bit difficult to match the parts of your code to the ideas in Section 3 of your paper. 
A brief documentation would help significantly in gaining a better understanding.

Thank you in Advance :)

**Comment by OhadRubin** [comment]
I added a bit of documentation for the forward pass here c3be64168523ade5809d84e920e8401bdafa6c2f.
If you have any specific questions, let me know.

**Comment by awasthiabhijeet** [comment]
Sure, thanks! :)
