### ISSUE TITLE
What are the uses of the function compute_beam_idx and compute_op_idx durin training ?

### ISSUE THREAD

**Issue by ali6947** [OhadRubin/SmBop#33]

**Comment by OhadRubin** [comment]
Well, we when we score the frontier, which is a vector of size U*K+B*K^2 of scalars, which is all possible combination(and applying an operation) of the beam, both of these functions return a list of size U*K+B*K^2. Where K is the beam size and U,B are the number of unary and binary operations.

`compute_beam_idx` computes which elements from the beam is a given score, and `compute_op_idx` computes what operation that score represents.
