### ISSUE TITLE
Running SmBoP in multi-threaded contexts

### ISSUE THREAD

**Issue by spectraldoy** [OhadRubin/SmBop#34]
I'm trying to write a Flask web app where I want to write out some english text, translate it to SQL using an SmBoP model, and execute it on my backend database. However, Flask seems to create multiple threads to run the app, and when I try to run the model through the web app I get the following SQLite3 error:
```
ProgrammingError: SQLite objects created in a thread can only be used in that same thread
```
This seems to be caused by SmBoP's `enc_preproc` functionality accessing the SQLite database from multiple threads. After some research, following a suggestion from [this stackoverflow question](https://stackoverflow.com/questions/48218065/programmingerror-sqlite-objects-created-in-a-thread-can-only-be-used-in-that-sa), I found that changing lines 185-186 of `smbop/dataset_readers/enc_preproc.py` from:
```python
with sqlite3.connect(sqlite_path) as source:
    dest = sqlite3.connect(":memory:")
```
to:
```python
with sqlite3.connect(sqlite_path, check_same_thread=False) as source:
    dest = sqlite3.connect(":memory:", check_same_thread=False)
```
solved my problem. Would it be possible to include this in the official codebase so that I can just clone the repository when I need it, and can properly keep my clone up to date, or are there reasons to avoid this type of change?

**Comment by OhadRubin** [comment]
Sure, make a pull request and i'll approve it.

**Comment by spectraldoy** [comment]
Great, thank you so much! 

Also, I ran the eval.py test script on the Spider dataset on a single thread after making the change and it gives the same accuracy results as without the change to the code, which is reassuring. I haven't run the script in a multi-threaded environment yet, but at least we know the accuracy is preserved in a single-threaded context with this change.
