### ISSUE TITLE
Do we have to create the schema manually for the custom database or is there any way to generate sqlite schema?

### ISSUE THREAD

**Issue by alan-ai-learner** [OhadRubin/SmBop#39]

**Comment by OhadRubin** [comment]
Sorry..., I don't really have experience with fine-tuning. 
@hXtreme can you maybe help him?

**Comment by alan-ai-learner** [comment]
Thanks for your reply, I just wanna use your model with my custom database , so I know the process, but don't know  how can make a schema for my database to append in table.json file.

**Comment by hXtreme** [comment]
@alan-ai-learner You can find the format of what you need to append to table.json on the spider repo.

As far as I know you have to do it manually.

All but the column name and table name columns can theoretically be auto generated. These two contain natural language name of the column/table respectively.

For example, if column(column name original) at index 5 was aid then column name might be "airline id"

If you write a script to automate this to some extent then please share it with me and ideally make a pr on spider's repo or here. I think this is something that would benefit a lot of people.

**Comment by alan-ai-learner** [comment]
so @hXtreme  I did write an script that need the sqlite file and generate the json output, I was able to generate everything except the primary and foreign keys, I was trying but won't be able to came up with any logic that can extract the keys from the sqlite file, as they mentioned in the table.json file on spider repo. If you can help me on getting the keys that would be great, any help would be very much helpful.
Thanks

**Comment by hXtreme** [comment]
See if this helps:

https://stackoverflow.com/questions/54412977/sqlite3-python-get-list-of-primary-and-foreign-keys

Best,
Harsh

**Comment by alan-ai-learner** [comment]
`import sqlite3
from collections import OrderedDict

#Variables
db_schema = {}
db_filename = input("enter path to the sqlite file or name of the file if you are in same directory:--")
sc_keys = ['column_names', 'column_names_original', 'column_types', 'db_id', 'foreign_keys', 'primary_keys', 'table_names', 'table_names_original']


db=sqlite3.connect(db_filename)
db.text_factory = str
cur = db.cursor()

result = cur.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
table_names = list(zip(*result))[0]

def column_json(table_names):
  columns = [[-1,"*"],]
  for i, table_name in enumerate(table_names):
      result = cur.execute("PRAGMA table_info('%s')" % table_name).fetchall()
      column_names = list(zip(*result))[1]
      for j in column_names:
        columns.append([i , j])
  return columns

def columns_datatype(table_names):
   col_data_type = []
   for table_name in table_names:
    data_types = cur.execute(f'PRAGMA TABLE_INFO({table_name})').fetchall()
    # foreign_keys = cur.execute(f'PRAGMA foreign_key_list({table_name})').fetchall()
    # print(foreign_keys)
    for i in data_types:
      col_data_type.append(i[2].split('(')[0])  
    for i,j in enumerate(col_data_type):
       if j == 'varchar':
         col_data_type[i] = 'text'
       elif j == 'numeric':
         col_data_type[i] = 'number'
       
   return col_data_type 


#Creating the json,
db_schema = {}
for i in sc_keys:
  if i == 'table_names':
    db_schema["table_names"] = list(table_names)
  elif i == 'table_names_original':
    db_schema["table_names_original"] =  [i.title() for i in list(table_names)]
  elif i == 'column_names':
    db_schema["column_names"] = column_json(table_names)
  elif i == 'column_names_original':
    db_schema["column_names_original"] = column_json(table_names)
  elif i == 'column_types':
    db_schema["column_types"] = columns_datatype(table_names)
  elif i == 'db_id':
    try:
      db_schema["db_id"] = (db_filename.split('/')[-1]).split('.')[0]
    except:
      db_schema["db_id"] = db_filename.split('.')[0]
  elif i == 'foreign_keys':
    db_schema["foreign_keys"] = []
  elif i == 'primary_keys':
    db_schema["primary_keys"] = []

# rearranging the schema

ordered = OrderedDict()
for k in sc_keys:
    ordered[k] = db_schema[k]

#Dumping as json
import json
print(json.dumps(db_schema))`



> @alan-ai-learner You can find the format of what you need to append to table.json on the spider repo.
> 
> As far as I know you have to do it manually.
> 
> All but the column name and table name columns can theoretically be auto generated. These two contain natural language name of the column/table respectively.
> 
> For example, if column(column name original) at index 5 was aid then column name might be "airline id"
> 
> If you write a script to automate this to some extent then please share it with me and ideally make a pr on spider's repo or here. I think this is something that would benefit a lot of people.

**Comment by alan-ai-learner** [comment]
this is the final link  [link](https://github.com/alan-ai-learner/schema_gen_spider/blob/main/schema_generator.py)
to the script to the  I wrote. It will generate the json.

**Comment by alan-ai-learner** [comment]
co

**Comment by alan-ai-learner** [comment]
@hXtreme  Hey,  is there any script to create a train_spider.json format dataset? Can you pls suggest if any.

Thanks.

**Comment by hXtreme** [comment]
none to the best of my knowledge.

**Comment by alan-ai-learner** [comment]
> none to the best of my knowledge.

Hi @hXtreme, @OhadRubin  , i managed to make the custom data set, but im unable to understand one field  "sql" in the train_spider.json.There is an script [preprocess/parse_one_sql.py](https://github.com/taoyds/spider/blob/master/preprocess/parse_sql_one.py) in the spider repo to generate it, but it wasn't supporting this query ,"SELECT DATE_FORMAT(date_complaint_raised,'%Y-%m'), count(*) FROM Complaints WHERE YEAR(date_complaint_raised) = value GROUP BY DATE_FORMAT(date_complaint_raised,'%Y-%m')", it gives some [date-format](![spider_err](https://user-images.githubusercontent.com/53686128/132245919-c462652f-6972-497b-90fb-ea3b488c60a7.png)) assertion error. Can you please look into it?
Thanks
![spider_err](https://user-images.githubusercontent.com/53686128/132246029-f98138e1-e6af-485d-ba5f-24d89f394c93.png)

**Comment by hXtreme** [comment]
To the best of my knowledge, date is not a standard sqlite data type.

**Comment by alan-ai-learner** [comment]
> To the best of my knowledge, date is not a standard sqlite data type.

so what can we do, any alternative you can think of?

**Comment by alan-ai-learner** [comment]
> > none to the best of my knowledge.
> 
> Hi @hXtreme, @OhadRubin , i managed to make the custom data set, but im unable to understand one field "sql" in the train_spider.json.There is an script [preprocess/parse_one_sql.py](https://github.com/taoyds/spider/blob/master/preprocess/parse_sql_one.py) in the spider repo to generate it, but it wasn't supporting this query ,"SELECT DATE_FORMAT(date_complaint_raised,'%Y-%m'), count(*) FROM Complaints WHERE YEAR(date_complaint_raised) = value GROUP BY DATE_FORMAT(date_complaint_raised,'%Y-%m')", it gives some date-format assertion error. Can you please look into it?
> Thanks
> ![spider_err](https://user-images.githubusercontent.com/53686128/132246029-f98138e1-e6af-485d-ba5f-24d89f394c93.png)

@hXtreme @yonatansito @Muradean  any suggestion on this?
