### ISSUE TITLE
How can I change the parameters if the cuda memery is not enough?

### ISSUE THREAD

**Issue by programmerGeGe** [OhadRubin/SmBop#44]
![image](https://user-images.githubusercontent.com/44105821/130789730-2e7aeda1-af6f-4e6c-ae1c-c93165209535.png)
Even I change the batch size to 1,it still raises  this error 。And my cuda memery is 6 G

**Comment by OhadRubin** [comment]
Do you want to perform inference? Or to further train the model?

**Comment by programmerGeGe** [comment]
Thanks for reply.I use the exec.py to train a model.

**Comment by alan-ai-learner** [comment]
> Thanks for reply.I use the exec.py to train a model.

hey on which dataset are you trying to train it?

**Comment by programmerGeGe** [comment]
> > Thanks for reply.I use the exec.py to train a model.
> 
> hey on which dataset are you trying to train it?

the spider dataset

**Comment by alan-ai-learner** [comment]
> > > Thanks for reply.I use the exec.py to train a model.
> > 
> > hey on which dataset are you trying to train it?
> 
> the spider dataset 

What makes you to train the model again, is the provided model in this repo is not performing well ?
Can try to look at this issue https://github.com/OhadRubin/SmBop/issues/45#issue-981706319

**Comment by OhadRubin** [comment]
Hey @programmerGeGe, sadly, I don't really have any good advice other then get a GPU with more memory (12GB should be enough).
Sorry
