### ISSUE TITLE
Is SmBop can adapt the database functions and  it not detecting the date columns in data base?

### ISSUE THREAD

**Issue by alan-ai-learner** [OhadRubin/SmBop#45]
it looks like the model doesn't support some important functions like strftime() which are quite common while doing, say, a monthwise or yearwise aggregation query. Can the model be trained to support it

**Comment by OhadRubin** [comment]
Sure, you can add training examples that support it and modify SmBop to handle those operations.

**Comment by alan-ai-learner** [comment]
Thanks alot, for your confirmation. we will work on that.

**Comment by alan-ai-learner** [comment]
@OhadRubin  Is there any way to create the train_spider.json dataset, like spider has there repo, but im unable to find any way to utilize that for generating the custom dataset. 

Thanks

**Comment by alan-ai-learner** [comment]
> Sure, you can add training examples that support it and modify SmBop to handle those operations.

can you suggest some ways to add the sample, for the functions. I #50
