### ISSUE TITLE
How  can we new sample to spider dataset to fine tune the SmBop?

### ISSUE THREAD

**Issue by alan-ai-learner** [OhadRubin/SmBop#50]
> none to the best of my knowledge.

Hi @hXtreme, @OhadRubin  , I managed to make the custom data set, but I'm facing some problems:
1. I'm unable to understand one field  ```sql:{}```in the train_spider.json . Can you please explain how you were utilizing this in SmBop , what role is playing in the spider dataset? and is it needed in SmBop or not?

2. There is an script in the spider repository, [preprocess/parse_one_sql.py](https://github.com/taoyds/spider/blob/master/preprocess/parse_sql_one.py)  to generate this parsed sql query and it is working perfectly for some queries, but when i tried this query ,```SELECT DATE_FORMAT(date_complaint_raised,'%Y-%m'), count(*) FROM Complaints WHERE YEAR(date_complaint_raised) = value GROUP BY DATE_FORMAT(date_complaint_raised,'%Y-%m')```, it gives some [date-format](![spider_err](https://user-images.githubusercontent.com/53686128/132245919-c462652f-6972-497b-90fb-ea3b488c60a7.png)) assertion error. So while going through the code i found out the [script](https://github.com/taoyds/spider/blob/master/process_sql.py) is hard coded, and not supporting functions, So what can we do to add function. 
Thanks
![spider_err](https://user-images.githubusercontent.com/53686128/132246029-f98138e1-e6af-485d-ba5f-24d89f394c93.png)

PS: The ```strftime``` function in sqlite is also not working.
_Originally posted by @alan-ai-learner in https://github.com/OhadRubin/SmBop/issues/39#issuecomment-913764745_

**Comment by OhadRubin** [comment]
Sorry, this seems like a question for the guys who wrote spider pre-processing script...

**Comment by alan-ai-learner** [comment]
> Sorry, this seems like a question for the guys who wrote spider pre-processing script...



I'm unable to understand one field sql:{}in the train_spider.json . Can you please explain how you were utilizing this in SmBop , what role is playing in the spider dataset? and is it needed in SmBop or not?

Like i tried to connect with them but, they seems like offline by last one year, so i was for understanding the datasets more.
So i thought you may help. Mostly the parsing part in the dataset im unable to understand.

**Comment by OhadRubin** [comment]
The "sql" field is the output of a SQL to parser (i.e SQL-to-AST) that the dataset creators supplied, I don't think I'm using this anywhere in my code.
