### ISSUE TITLE
Can't download spider and model_weights

### ISSUE THREAD

**Issue by fjakob** [OhadRubin/SmBop#61]
There is a problem with the permissions of the gdown files:
  
  Permission denied: https://drive.google.com/uc?export=download&id=1_AckYkinAnhqmRQtGsQgUKAnTHxxX5J0
  Maybe you need to change permission over 'Anyone with the link'?

Of course I could download it via the browser, however, I need the files on an ssh server, where I dont have browser access. How do I solve this?

**Comment by OhadRubin** [comment]
actually, this spider.zip file is not on my google drive. it is the link from the offical website here: https://yale-lily.github.io/spider
But if you really need to download it to a remote server, you can get around the google drive thing by doing the following:
1. clicking the "download anyway" button on that google drive link
2. clicking cancel on the pop-up
3. going to chrome developer tools -> network and clicking on downlad?... (see picture)-> copy all as curl

<img width="756" alt="Screenshot 2024-01-12 at 21 49 47" src="https://github.com/OhadRubin/SmBop/assets/4252994/12d7d8b8-fae9-4658-a596-9ad6c41b1643">
