### ISSUE TITLE
Resuming model training

### ISSUE THREAD

**Issue by Muradean** [OhadRubin/SmBop#7]
Hi,

First of all, Thanks for your work.

I've managed to train the model for 100 epochs, but I would like to continue. I noticed you prepared a script "resume.py" but when I try running it, after changing the serialization_dir:

![a](https://user-images.githubusercontent.com/14300941/117560077-88a9d280-b082-11eb-9bb0-00ede4ee3251.png)

I got some errors with the imports, so I commented them:

![a](https://user-images.githubusercontent.com/14300941/117560091-a840fb00-b082-11eb-9803-f683e5920d84.png)

However, when running resume.py I now get this error:

![a](https://user-images.githubusercontent.com/14300941/117560107-d4f51280-b082-11eb-8500-21cd9ee3aa24.png)

Any clue on how to solve it @OhadRubin ?

Thanks a lot

**Comment by Muradean** [comment]
After replacing the imports of resume.py with those present in exec.py:
![a](https://user-images.githubusercontent.com/14300941/117560460-da079100-b085-11eb-8a8f-794afc8c0cf6.png)
I managed to resume.py to run further, but it still got an exception because was missing a file:
![a](https://user-images.githubusercontent.com/14300941/117560625-50f15980-b087-11eb-9e78-9dfb90f1399c.png)
So I took a look at my experiments folder and since the file for the 100th iteration was missing:
![a](https://user-images.githubusercontent.com/14300941/117560660-aded0f80-b087-11eb-8634-b0a6c5970ea4.png)
 I renamed training_state_epoch_99.th to training_state_epoch_100.th and managed to resume train sucessfully.

**Comment by Muradean** [comment]
I created a pull request in case you want to merge:
https://github.com/OhadRubin/SmBop/pull/8

**Comment by OhadRubin** [comment]
Hey Pedro!
Sorry for the wonky code! And thank you for the pull request!
I polished resume.py some more merged my own changes here https://github.com/OhadRubin/SmBop/commit/4064127567ddd589b3690292fc3ac83fb9d0a1a4 .
